name: release
on:
	push:
		branches:
			- main
		tags:
			- v*
jobs:
	linux-release:
		runs-on: ubuntu-latest
		steps:
			- name: Clone repository
				uses: actions/checkout@v4
			- name: Set up Flutter
				uses: subosito/flutter-action@v2
				with:
					channel: stable
					flutter-version: 3.24.5
			- run: flutter build linux

