name: release
on:
  push:
    tags:
      - '*'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: 3.24.5
      - run: flutter pub get
      - run: flutter build linux
      - run: tar -cf "pffs-$(git describe --tags --abbrev=0).tar.gz" ./build/linux/x64/release/bundle/*
			- name: Upload artifact
			- uses: actions/upload-artifact@v4
      	with:
          name: artifact-linux
          path: "pffs-$(git describe --tags --abbrev=0).tar.gz"
	release:
		needs: build-linux
		runs-on: ubuntu-latest
		steps:
			- uses: actions/download-artifact@v4
        with:
          name: artifact-linux
			- run: ls
			- run: gh --help

#  build-apk:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v4
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: stable
#          cache: true
#          flutter-version: 3.24.5
#      - run: flutter pub get
#      - run: flutter build apk
#  build-windows:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v4
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: stable
#          cache: true
#          flutter-version: 3.24.5
#      - run: flutter pub get
#      - run: flutter build windows
#
