name: release
on:
  push:
    tags:
      - '*'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          flutter-version: 3.24.5
      - run: | 
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libmpv2
          flutter pub get
          flutter build linux
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-linux
          path: ./build/linux/x64/release/bundle/
  release:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact-linux
      - run: ls
      - run: gh --help

#  build-apk:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v4
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: stable
#          cache: true
#          flutter-version: 3.24.5
#      - run: flutter pub get
#      - run: flutter build apk
#  build-windows:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v4
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: stable
#          cache: true
#          flutter-version: 3.24.5
#      - run: flutter pub get
#      - run: flutter build windows
#
