name: release
on:
  push:
    tags:
      - '*'
jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags 
      - id: get_version
        run: |
          echo "version=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
      
    
  build-linux:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: 3.24.5
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: dia ninja-build libgtk-3-dev libmpv2 libmpv-dev mpv
          version: 1.0
      - run: |
          flutter pub get
          flutter build linux
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pffs-linux-bundle-${{ needs.get-version.outputs.version }}
          path: ./build/linux/x64/release/bundle/

  build-apk:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: 3.24.5
      - run: |
          flutter pub get
          flutter build apk
          mv ./build/app/outputs/flutter-apk/app-release.apk ./build/app/outputs/flutter-apk/pffs-${{ needs.get-version.outputs.version }}.apk 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pffs-apk-${{ needs.get-version.outputs.version }}
          path: ./build/app/outputs/flutter-apk/pffs-${{ needs.get-version.outputs.version }}.apk

  build-windows:
    runs-on: windows-latest
    needs: get-version
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: 3.24.5
      - run: | 
          flutter pub get
          flutter build windows
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pffs-windows-bundle-${{ needs.get-version.outputs.version }}
          path: ./build/windows/x64/runner/Release/

  release:
    env:
      GH_TOKEN: ${{ github.token }}
    needs: 
      - get-version
      - build-linux
      - build-windows
      - build-apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: pffs-*-${{ needs.get-version.outputs.version }}
          path: pffs-linux-bundle-${{ needs.get-version.outputs.version }}
      - run: |
          ls
          tar -cf pffs-linux-bundle-${{ needs.get-version.outputs.version }}.tar.gz pffs-linux-bundle-${{ needs.get-version.outputs.version }}/* 
          zip pffs-windows-bundle-${{ needs.get-version.outputs.version }}.zip pffs-windows-bundle-${{ needs.get-version.outputs.version }}/*
      - run: |
          gh release create -d -R GachiLord/pffs \
            ${{ needs.get-version.outputs.version }} \ 
            pffs-linux-bundle-${{ needs.get-version.outputs.version }}.tar.gz \
            pffs-windows-bundle-${{ needs.get-version.outputs.version }}.zip \
            pffs-${{ needs.get-version.outputs.version }}.apk

